version: "3.7"

services:
  frontend:
    build: ./client
    volumes:
      - ./client:/app:cached
      - frontend:/app/dist
    ports:
      - "3000:3000"
      - "8080:8080"
    command: sh -c "yarn && yarn start"
  api:
    build: ./api
    volumes:
      - ./api:/app:cached
      - api:/app/dist
    ports:
      - "8000:8000"
    command: sh -c "yarn && yarn start"

volumes:
  frontend:
  api:
