version: '3.7'

services:
  frontend:
    build: ./
    volumes:
      - ./:/app:cached
      - frontend:/app/dist
    ports:
      - '3000:3000'
      - '8080:8080'
    command: sh -c "yarn && yarn start"

volumes:
  frontend:
